### ISSUE TITLE
[MVP]: Create social media button container

### ISSUE THREAD

**Issue by e2nguyen** [e2nguyen/Watcher#45]
## Description
Every post will have our social media buttons laid out in the same format. Let's create a container for this to essentially set the styling.

## Branches
`create_social_media_container_45`

## Requires
- #41
- #42

## Tasks
- [x] create a `SocialMediaButtonContainer` component that contains the social media buttons laid out horizontally
- [x] update the button component to have a span as a container 
   - this way we make our buttons inline elements and buttons can sit horizontally

## PR
#46

**Comment by dianephan** [comment]
![image](https://user-images.githubusercontent.com/17483220/111080155-66e50280-84ba-11eb-9904-7d8c69b5c29d.png)
